tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "mongodb/brew"
tap "sambadevi/powerlevel9k"
# Library and utilities for processing GIFs
brew "giflib"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Collection of portable C++ source libraries
brew "boost"
# XML-based font configuration API for X Windows
brew "fontconfig"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# Tool to obtain certs from Let's Encrypt and autoenable HTTPS
brew "certbot"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Pack, ship and run any application as a lightweight container
brew "docker"
# VMware Fusion & Workstation docker-machine driver
brew "docker-machine-driver-vmware"
# Collection of reusable C++ library artifacts developed at Facebook
brew "folly"
# C++14 implementation of the TLS-1.3 standard
brew "fizz"
# Modular, composable client/server abstractions framework
brew "wangle"
# Facebook's branch of Apache Thrift, including a new C++ server
brew "fbthrift"
# Thrift functions for querying information from a service
brew "fb303"
# Shared library for Watchman and Eden projects
brew "edencommon"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Cross-platform application and UI framework
brew "qt"
# Command-driven, interactive function plotting
brew "gnuplot"
# Manage compile and link flags for libraries
brew "pkg-config"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Image manipulation library
brew "jpeg", link: true
# Provides library functionality for FIDO U2F & FIDO 2.0, including USB
brew "libfido2"
# X.509 and CMS library
brew "libksba"
# Library to render SVG files using Cairo
brew "librsvg"
# Generic library support script
brew "libtool"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Platform built on V8 to build network applications
brew "node", link: false
# MongoDB Shell to connect, configure, query, and work with your MongoDB database
brew "mongosh"
# UNIX movie player
brew "mplayer"
# Open source relational database management system
brew "mysql"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Platform built on V8 to build network applications
brew "node@14"
# Platform built on V8 to build network applications
brew "node@16"
# Manage multiple Node.js versions
brew "nvm"
# Object-relational database system
brew "postgresql@14", link: false
# Interpreted, interactive, object-oriented programming language
brew "python@3.11", link: false
# Interpreted, interactive, object-oriented programming language
brew "python@3.9", link: false
# Cross-platform application and UI framework
brew "qt@5"
# Ruby version manager
brew "rbenv"
# Persistent key-value database, with built-in net interface
brew "redis"
# Rename multiple files in a directory
brew "ren"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# High-performance, schema-free, document-oriented database
brew "mongodb/brew/mongodb-community"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# File system integration
cask "macfuse"
# Minimal installer for conda specific to conda-forge
cask "miniforge"
# OpenJDK distribution from Azul
cask "zulu@11"
vscode "abusaidm.html-snippets"
vscode "andrewdircks.google-cloud-platform-ssh"
vscode "apollographql.vscode-apollo"
vscode "astro-build.astro-vscode"
vscode "belkacemberras.spellcheck"
vscode "binarybytes.snippets"
vscode "bradlc.vscode-tailwindcss"
vscode "burkeholland.simple-react-snippets"
vscode "caolin.java-run"
vscode "chris-noring.node-snippets"
vscode "christian-kohler.npm-intellisense"
vscode "cschlosser.doxdocgen"
vscode "danielpinto8zz6.c-cpp-compile-run"
vscode "dbaeumer.vscode-eslint"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "eliverlara.andromeda"
vscode "esbenp.prettier-vscode"
vscode "expresssnippets.vscode-express-snippets"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "hdoro.sanity-snippets"
vscode "josetr.cmake-language-support-vscode"
vscode "juanblanco.solidity"
vscode "kvcvc.sequelize-snippets"
vscode "lucianirsigler.nasm"
vscode "mathiasfrohlich.kotlin"
vscode "mechatroner.rainbow-csv"
vscode "meganrogge.template-string-converter"
vscode "mhutchie.git-graph"
vscode "moalamri.inline-fold"
vscode "mongodb.mongodb-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-ossdata.vscode-postgresql"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-vsliveshare.vsliveshare"
vscode "msjsdiag.vscode-react-native"
vscode "mtxr.sqltools"
vscode "nucllear.vscode-extension-auto-import"
vscode "pkief.material-icon-theme"
vscode "pranaygp.vscode-css-peek"
vscode "rangav.vscode-thunder-client"
vscode "rebornix.prolog"
vscode "redhat.java"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rights.nas-vscode"
vscode "ritwickdey.liveserver"
vscode "sanity-io.vscode-sanity"
vscode "snlbaral.express-mongo-snippets"
vscode "tabnine.tabnine-vscode"
vscode "tomoki1207.pdf"
vscode "trufflesuite-csi.truffle-vscode"
vscode "twxs.cmake"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vmsynkov.colonize"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "wix.vscode-import-cost"
vscode "xabikos.javascriptsnippets"
